namespace Shared;

public enum ExitCode
{
	Success = 0,
	InvalidParameter,
	CallOnInvalidCondition,
	ServerNoValidLocalhostIp,
	ConnectionToServerFailed,
	DisconnectedFromServer,
	MessageSendingTimeout,
	MessageReceivingTimeout,
	MessageReceivedCorrupted,
	MessageNotReceived,
	InvalidMessageData,
	DatabaseStartupFailed,
	DatabaseShutdownFailed,
	DatabaseOperationFailed,
	UserDoesntExist,
	VmAlreadyExists,
	VmDoesntExist,
	VmAlreadyRunning,
	VmStartupFailed,
	VmIsShutDown,
	VmScreenStreamNotRunning,
	VmScreenStreamAlreadyRunning,
	VmScreenStreamStartFailed,
	VmScreenStreamStopFailed,
	VmScreenStreamUnsupportedPixelFormat,
	TooManyVmsRunning,
	VncConnectionFailed,
	DriveAlreadyExists,
	DriveDoesntExist,
	DriveConnectionAlreadyExists,
	DiskImageCreationFailed,
}